# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserList',
        ),
    ]
