# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userlist_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('pname', models.CharField(max_length=20)),
                ('teaname', models.CharField(max_length=20)),
                ('stulist', models.CharField(max_length=10240)),
                ('prolist', models.CharField(max_length=10240)),
                ('penabled', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='userlist',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
