# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20181121_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperid', models.CharField(max_length=20)),
                ('stuid', models.CharField(max_length=20)),
                ('submit_time', models.CharField(max_length=20)),
                ('answers', models.CharField(max_length=10240)),
                ('keguan_grade', models.IntegerField()),
                ('keguan_detail', models.CharField(max_length=10240)),
                ('zhuguan_grade', models.IntegerField()),
                ('zhuguan_detail', models.CharField(max_length=10240)),
                ('total_score', models.IntegerField()),
            ],
        ),
    ]
