# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_testrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='confirmed',
            field=models.CharField(default='no', max_length=20),
            preserve_default=False,
        ),
    ]
